- name: install packages
  ansible.builtin.package:
    name:
      - htop
      - vim
      - nmap

# - name: get the username running the deploy
#   become: false
#   local_action: command whoami
#   register: username_on_the_host
