- name: Check brew path
  ansible.builtin.find:
    paths: /home
    file_type: file
    use_regex: yes
    recurse: true
    patterns:
      - 'brew'
      # - '^[a-z]{1,5}_.*log$'
  register: brew_path

- name: Install brew packages
  community.general.homebrew:
    name: maven
    path: "{{ brew_path.stdout }}"
    state: present
    update_homebrew: true
