- name: Check brew path
  ansible.builtin.find:
    paths: /home
    file_type: link
    use_regex: true
    recurse: true
    patterns:
      # - "{{ 'brew' | regex_escape() }}"
      - '^//bin//brew$'
      # - '^[a-z]{1,5}_.*log$'
  register: brew_path

- name: Install brew packages
  community.general.homebrew:
    name: maven
    path: "{{ brew_path.files.path }}"
    state: present
    update_homebrew: true
