- name: Check brew path
  command: which bash
  # command: echo hello
  ignore_errors: true
  register: brew_path

- name: Install brew packages
  community.general.homebrew:
    name: maven
    path: "{{ brew_path.stdout }}"
    state: present
    update_homebrew: true
